name: clone_instagram
description: "Instagram profile page clone"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cloud_firestore: ^4.15.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: any
  mockito: ^5.0.0

flutter:
  uses-material-design: true